Networkteam:
  Neos:
    Next:
      # Configure Next.js setting by site node name
      sites:
        # The default settings are used for all sites without a specific configuration
        _default:
          # The base URL for the Next.js frontend
          nextBaseUrl: http://localhost:3000/

          revalidate:
            # The URI for revalidation could be a path or an absolute URL
            uri: '/api/revalidate'
            token: 'a-secret-token'

          # A list of site nodes to additionally revalidate with an empty list of invalidated documents
          # (this is rarely needed, e.g. only if nodes are referenced cross-site)
          extraRevalidateSites: []

        # Add additional site configurations by site node name
        #
        # mySiteNode:
        #   nextBaseUrl: http://my-site.local:3000/

Neos:

  Neos:
    fusion:
      autoInclude:
        'Networkteam.Neos.Next': true
